spring:
  application:
    name: tenable-mcp
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:tenable}  # Default to tenable profile if not specified

server:
  port: 8080

# Common configurations
tenable:
  timeout: 30000
  maxRetries: 3

logging:
  level:
    com.tenable.mcp: DEBUG
    org.springframework.web: INFO 